In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.5

In [3]:
print(pd.Series(5))

'''
0    5
dtype: int64
'''

print(pd.Series(5, index=["a", "b", "c"]))

'''
a    5
b    5
c    5
dtype: int64
'''

0    5
dtype: int64
a    5
b    5
c    5
dtype: int64

'\na    5\nb    5\nc    5\ndtype: int64\n'

In [7]:
import pandas as pd

# 리스트를 사용한 시리즈 생성 (인덱스 직접 지정)
population = pd.Series([940, 330, 290], index=['서울', '부산', '인천'])
print(population)


# index 확인하기
print(population.index)   # Index(['서울', '부산', '인천'], dtype='str')

# 배열 확인하기
print(population.values)   # [940 330 290]

서울    940
부산    330
인천    290
dtype: int64
Index(['서울', '부산', '인천'], dtype='str')
[940 330 290]

In [8]:

# k:v 구조를 갖는 딕셔너리를 만들고, 변수 dict_data에 저장
dict_data = {'a': 1, 'b': 2, 'c': 3}
print(dict_data)            # {'a': 1, 'b': 2, 'c': 3}

# 판다스 Series() 함수로 딕셔너리(dict_data)를 시리즈로 변환. 변수 sr에 저장
sr = pd.Series(dict_data)

# 변수 sr의 자료형 출력
print(type(sr))            # <class 'pandas.core.series.Series'>

# 주피터 환경에서 변수 출력
print(sr)

# 인덱스 배열은 변수 idx에 저장
idx = sr.index
print(idx)

# 데이터 값 배열은 변수 val에 저장
val = sr.values
print(val)

{'a': 1, 'b': 2, 'c': 3}
<class 'pandas.Series'>
a    1
b    2
c    3
dtype: int64
Index(['a', 'b', 'c'], dtype='str')
[1 2 3]

In [9]:
import pandas as pd

# 리스트를 시리즈로 변환하여 변수 sr에 저장
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr)

'''
0    2019-01-02
1          3.14
2           ABC
3           100
4          True
'''

# 인덱스 배열은 변수 idx에 저장
idx = sr.index
print(idx)                         # RangeIndex(start=0, stop=5, step=1)

# 데이터 값 배열은 변수 val에 저장
val = sr.values
print(val)                         # ['2019-01-02' 3.14 'ABC' 100 True]

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object
RangeIndex(start=0, stop=5, step=1)
['2019-01-02' 3.14 'ABC' 100 True]

In [10]:
import pandas as pd

# 투플을 시리즈로 변환(index 옵션에 인덱스 이름을 지정)
tup_data = ('영인', '2010-05-01', '여', True)
sr = pd.Series(tup_data, index=['이름', '생년월일', '성별', '학생여부'])
print(sr)

'''
이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object
'''

# 인덱스 배열은 변수 idx에 저장
idx = sr.index
print(idx)           # Index(['이름', '생년월일', '성별', '학생여부'], dtype='str')

# 데이터 값 배열은 변수 val에 저장
val = sr.values
print(val)            # ['영인' '2010-05-01' '여' True]


sr = pd.Series(tup_data)
# 인덱스 배열은 변수 idx에 저장
idx = sr.index
print(idx)              # RangeIndex(start=0, stop=4, step=1

# 데이터 값 배열은 변수 val에 저장
val = sr.values
print(val)              # ['영인' '2010-05-01' '여' True]

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object
Index(['이름', '생년월일', '성별', '학생여부'], dtype='str')
['영인' '2010-05-01' '여' True]
RangeIndex(start=0, stop=4, step=1)
['영인' '2010-05-01' '여' True]

In [11]:
import pandas as pd

# 열이름을 key로 하고, 리스트를 value로 갖는 딕셔너리 정의(2차원 배열)
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

# 판다스 DataFrame() 함수로 딕셔너리를 데이터프레임으로 변환. 변수 df에 저장.
df = pd.DataFrame(dict_data)

# df의 자료형 출력
print(type(df))


# 변수 df에 저장되어 있는 데이터프레임 객체를 출력
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [15]:
# 딕셔너리를 사용한 데이터프레임 생성
data = {'나이': [19,30,40] , '직업': ['학생', '회사원', '연구원']}
df = pd.DataFrame(data, index=['철수', '영희', '민수'])
print(df)



#행 인덱스 확인하기
print(df.index)      

#열 이름 확인하기
print(df.columns)

    나이   직업
철수  19   학생
영희  30  회사원
민수  40  연구원
Index(['철수', '영희', '민수'], dtype='str')
Index(['나이', '직업'], dtype='str')

In [16]:
import pandas as pd

# 행 인덱스/열 이름 지정하여, 데이터프레임 만들기
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])

# 데이터프레임 출력하기
print(df)    

#행 인덱스 확인하기
print(df.index)      

#열 이름 확인하기
print(df.columns)  


# 행 인덱스, 열 이름 변경하기
df.index=['학생1', '학생2']
df.columns=['연령', '남녀', '소속']

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중
Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')
     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [17]:
import pandas as pd

# 행 인덱스/열 이름 지정하여, 데이터프레임 만들기
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])

# 행 인덱스, 열 이름 확인하기
print(df)

# 열 이름 중, '나이'를 '연령'으로, '성별'을 '남녀'로, '학교'를 '소속'으로 바꾸기
df = df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'})

# df 출력(변경 후)
print(df)

# df의 행 인덱스 중에서, '준서'를 '학생1'로, '예은'을 '학생2'로 바꾸기
df = df.rename(index={'준서':'학생1', '예은':'학생2' })

# df 출력(변경 후)
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중
    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중
     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [21]:
%%writefile source/num.txt
1,2,3,4,5
6,7,8,9,10

Writing source/num.txt

In [22]:
%cat source/num.txt

UsageError: Line magic function `%cat` not found.

In [26]:
# header 키워드를 지정하지 않고 호출했을 때는 무조건 파일의 첫 줄을 header로 처리한다.
data = pd.read_csv('./source/num.txt')
print(data)
print(type(data))

   1  2  3  4   5
0  6  7  8  9  10
<class 'pandas.DataFrame'>

In [24]:
# 읽어올 파일에 header가 없으면 header=None을 설정한다.
# header 파리미터의 default : 'infer' 이다.
data = pd.read_csv('./source/num.txt', header=None)
print(data)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [33]:
import pandas as pd

data = pd.read_csv(
    "./source/num.txt",
    header=None,
    names=["학생1", "학생2", "학생3", "학생4", "학생5"]
)

data.index = ["1반", "2반"]

print(data)

    학생1  학생2  학생3  학생4  학생5
1반    1    2    3    4    5
2반    6    7    8    9   10

In [28]:
%%writefile  source/read_csv_sample.csv
c0,c1,c2,c3,c4
1,2,3,4,5
6,7,8,9,10
11,12,13,14,15

Writing source/read_csv_sample.csv

In [29]:
# 경로 폴더의 모든 파일 목록 확인하기
import os
os.listdir("./source")

['num.txt', 'read_csv_sample.csv']

In [30]:
# 파일경로를 찾고, 변수 file_path에 저장 (문자열 결합)
file_path = './source/read_csv_sample.csv'

print(file_path)

./source/read_csv_sample.csv

In [34]:
df3 = pd.read_csv(file_path, index_col=None)
print(df3)

   c0  c1  c2  c3  c4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15

In [36]:
# read_csv() 함수로 데이터프레임 변환. 변수 df4에 저장. index_col='c0' 옵션
df4 = pd.read_csv(file_path, index_col='c1')
print(df4)

    c0  c2  c3  c4
c1
2    1   3   4   5
7    6   8   9  10
12  11  13  14  15

In [37]:
import openpyxl

In [38]:
import pandas as pd

# 1. 샘플 데이터 생성 (직원 정보 및 실적 데이터)
data = {
    '직원ID': ['EMP01', 'EMP02', 'EMP03', 'EMP04', 'EMP05'],
    '이름': ['김철수', '이영희', '박민수', '정수진', '최동현'],
    '부서': ['영업부', '개발부', '영업부', '마케팅부', '개발부'],
    '입사일': ['2021-03-01', '2019-05-15', '2022-01-10', '2020-11-01', '2023-02-01'],
    '월급(만원)': [350, 480, 310, 420, 330],
    '성과점수': [88.5, 92.0, 78.0, 95.5, 84.0]
}

df = pd.DataFrame(data)

# 2. 'Sheet1' 시트 명으로 'data.xlsx' 저장
df.to_excel('source/emp.xlsx', sheet_name='Sheet1', index=False)

print("'data.xlsx' 파일이 성공적으로 생성되었습니다!")

'data.xlsx' 파일이 성공적으로 생성되었습니다!

In [39]:
import pandas as pd

# 1. 샘플 데이터 생성 (직원 정보 및 실적 데이터)
data = {
    '직원ID': ['EMP01', 'EMP02', 'EMP03', 'EMP04', 'EMP05'],
    '이름': ['김철수', '이영희', '박민수', '정수진', '최동현'],
    '부서': ['영업부', '개발부', '영업부', '마케팅부', '개발부'],
    '입사일': ['2021-03-01', '2019-05-15', '2022-01-10', '2020-11-01', '2023-02-01'],
    '월급(만원)': [350, 480, 310, 420, 330],
    '성과점수': [88.5, 92.0, 78.0, 95.5, 84.0]
}

df = pd.DataFrame(data)

# 2. 'Sheet1' 시트 명으로 'data.xlsx' 저장
df.to_excel('source/emp.xlsx', sheet_name='Sheet1', index=False)

print("emp.xlsx 파일이 성공적으로 생성되었습니다!")

emp.xlsx 파일이 성공적으로 생성되었습니다!

In [40]:
# read_excel() 함수로 데이터프레임 변환: header=0 (default 옵션)
# openpyxl 설치 필요
df1 = pd.read_excel('./source/emp.xlsx', engine='openpyxl')          

# 데이터프레임 출력
df1.head()

    직원ID   이름    부서         입사일  월급(만원)  성과점수
0  EMP01  김철수   영업부  2021-03-01     350  88.5
1  EMP02  이영희   개발부  2019-05-15     480  92.0
2  EMP03  박민수   영업부  2022-01-10     310  78.0
3  EMP04  정수진  마케팅부  2020-11-01     420  95.5
4  EMP05  최동현   개발부  2023-02-01     330  84.0

In [41]:
import os
import json

# 1. source 디렉토리 생성
os.makedirs('source', exist_ok=True)

# 2. 샘플 데이터 작성
data = [
    {"직원ID": "EMP01", "이름": "김철수", "부서": "영업부", "직급": "대리", "입사일": "2021-03-01", "월급(만원)": 350, "성과점수": 88.5},
    {"직원ID": "EMP02", "이름": "이영희", "부서": "개발부", "직급": "과장", "입사일": "2019-05-15", "월급(만원)": 480, "성과점수": 92.0},
    {"직원ID": "EMP03", "이름": "박민수", "부서": "영업부", "직급": "사원", "입사일": "2022-01-10", "월급(만원)": 310, "성과점수": 78.0},
    {"직원ID": "EMP04", "이름": "정수진", "부서": "마케팅부", "직급": "차장", "입사일": "2020-11-01", "월급(만원)": 520, "성과점수": 95.5},
    {"직원ID": "EMP05", "이름": "최동현", "부서": "개발부", "직급": "사원", "입사일": "2023-02-01", "월급(만원)": 330, "성과점수": 84.0},
    {"직원ID": "EMP06", "이름": "강지훈", "부서": "기획부", "직급": "대리", "입사일": "2021-08-15", "월급(만원)": 380, "성과점수": 89.0}
]

# 3. JSON 파일 저장 (한글 깨짐 방지를 위해 ensure_ascii=False 및 encoding='utf-8' 사용)
with open('source/emp.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print("source/emp.json 파일이 성공적으로 생성되었습니다!")

source/emp.json 파일이 성공적으로 생성되었습니다!

In [42]:
import pandas as pd

# read_json() 함수로 데이터프레임 변환 
df = pd.read_json('./source/emp.json')  
print(df)

    직원ID   이름    부서  직급         입사일  월급(만원)  성과점수
0  EMP01  김철수   영업부  대리  2021-03-01     350  88.5
1  EMP02  이영희   개발부  과장  2019-05-15     480  92.0
2  EMP03  박민수   영업부  사원  2022-01-10     310  78.0
3  EMP04  정수진  마케팅부  차장  2020-11-01     520  95.5
4  EMP05  최동현   개발부  사원  2023-02-01     330  84.0
5  EMP06  강지훈   기획부  대리  2021-08-15     380  89.0

In [43]:
import os
import json

# 1. source 디렉토리 생성
os.makedirs('source', exist_ok=True)

# 2. 샘플 데이터 작성
data = {
    "이름": {
        "0": "김철수",
        "1": "이영희"
    },
    "부서": {
        "0": "영업부",
        "1": "개발부"
    },
    "월급": {
        "0": 350,
        "1": 480
    }
}

# 3. JSON 파일 저장 (한글 깨짐 방지를 위해 ensure_ascii=False 및 encoding='utf-8' 사용)
with open('source/emp2.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print("source/emp2.json 파일이 성공적으로 생성되었습니다!")

source/emp2.json 파일이 성공적으로 생성되었습니다!

In [44]:
import pandas as pd

# read_json() 함수로 데이터프레임 변환 
df = pd.read_json('./source/emp2.json', orient='index')  
print(df)

      0    1
이름  김철수  이영희
부서  영업부  개발부
월급  350  480

In [1]:
# header은 기본이 첫 줄을 컬럼명으로 가져오도록 설정이 되여 있기 때문에 header='infer' 생략 가능하다.
import pandas as pd

df= pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv')
print(df)

# 위에서부터 5개 행 조회
print(df.head())

# 위에서부터 3개 행 조회
print(df.head(3))

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [4]:
# 위에서부터 5개 행 조회
print(df.head())

# 위에서부터 3개 행 조회
print(df.head(3))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [5]:
# 무작위로 1개 행 추출
print(df.sample())

# 무작위로 3개 행 추출
print(df.sample(3))

# 전체 데이터의 20%를 무작위로 추출 (frac 파라미터 사용)
print(df.sample(frac=0.2))

# 실행할 때마다 동일한 난수 결과를 얻고 싶을 때 (random_state)
print(df.sample(3, random_state=42))

    total_bill  tip   sex smoker  day    time  size
27       12.69  2.0  Male     No  Sat  Dinner     2
     total_bill   tip     sex smoker   day    time  size
104       20.92  4.08  Female     No   Sat  Dinner     2
214       28.17  6.50  Female    Yes   Sat  Dinner     3
136       10.33  2.00  Female     No  Thur   Lunch     2
     total_bill   tip     sex smoker   day    time  size
73        25.28  5.00  Female    Yes   Sat  Dinner     2
166       20.76  2.24    Male     No   Sun  Dinner     2
148        9.78  1.73    Male     No  Thur   Lunch     2
223       15.98  3.00  Female     No   Fri   Lunch     3
136       10.33  2.00  Female     No  Thur   Lunch     2
181       23.33  5.65    Male    Yes   Sun  Dinner     2
83        32.68  5.00    Male    Yes  Thur   Lunch     2
209       12.76  2.23  Female    Yes   Sat  Dinner     2
17        16.29  3.71    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
76        17.92  3.08    Male    Yes   Sat  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
96        27.28  4.00    Male    Yes   Fri  Dinner     2
55        19.49  3.51    Male     No   Sun  Dinner     2
115       17.31  3.50  Female     No   Sun  Dinner     2
134       18.26  3.25  Female     No  Thur   Lunch     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
127       14.52  2.00  Female     No  Thur   Lunch     2
117       10.65  1.50  Female     No  Thur   Lunch     2
61        13.81  2.00    Male    Yes   Sat  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
174       16.82  4.00    Male    Yes   Sun  Dinner     2
152       17.26  2.74    Male     No   Sun  Dinner     3
173       31.85  3.18    Male    Yes   Sun  Dinner     2
91        22.49  3.50    Male     No   Fri  Dinner     2
175       32.90  3.11    Male    Yes   Sun  Dinner     2
165       24.52  3.48    Male     No   Sun  Dinner     3
146       18.64  1.36  Female     No  Thur   Lunch     3
45        18.29  3.00    Male     No   Sun  Dinner     2
80        19.44  3.00    Male    Yes  Thur   Lunch     2
14        14.83  3.02  Female     No   Sun  Dinner     2
86        13.03  2.00    Male     No  Thur   Lunch     2
25        17.81  2.34    Male     No   Sat  Dinner     4
15        21.58  3.92    Male     No   Sun  Dinner     2
191       19.81  4.19  Female    Yes  Thur   Lunch     2
70        12.02  1.97    Male     No   Sat  Dinner     2
90        28.97  3.00    Male    Yes   Fri  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
162       16.21  2.00  Female     No   Sun  Dinner     3
110       14.00  3.00    Male     No   Sat  Dinner     2
143       27.05  5.00  Female     No  Thur   Lunch     6
144       16.43  2.30  Female     No  Thur   Lunch     2
171       15.81  3.16    Male    Yes   Sat  Dinner     2
220       12.16  2.20    Male    Yes   Fri   Lunch     2
125       29.80  4.20  Female     No  Thur   Lunch     6
62        11.02  1.98    Male    Yes   Sat  Dinner     2
217       11.59  1.50    Male    Yes   Sat  Dinner     2
196       10.34  2.00    Male    Yes  Thur   Lunch     2
95        40.17  4.73    Male    Yes   Fri  Dinner     4
     total_bill   tip   sex smoker  day    time  size
24        19.82  3.18  Male     No  Sat  Dinner     2
6          8.77  2.00  Male     No  Sun  Dinner     2
153       24.55  2.00  Male     No  Sun  Dinner     4

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [7]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [8]:
# 1. 크기와 이름 확인 (속성)
print(df.shape)    # 몇 행 몇 열?
print(df.columns)  # 무슨 컬럼들이 있지?
print(df.index)    # 인덱스는 어떻게 되어있지?

# 2. 요약 및 통계 확인 (메서드)
df.info()          # 결측치나 데이터 타입은 괜찮나?
df.describe()      # 숫자 데이터들의 평균/최댓값/최솟값은 얼마지?

(244, 7)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')
RangeIndex(start=0, stop=244, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [2]:
row_0 = df.loc[0]

In [4]:
rows = df.loc[[0, 2]]
print(rows)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
2       21.01  3.50    Male     No  Sun  Dinner     3

In [5]:
slice_rows = df.loc[0:2]
print(slice_rows)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [7]:
sub_loc = df.loc[0:2, ['tip', 'day']]
print(sub_loc)

    tip  day
0  1.01  Sun
1  1.66  Sun
2  3.50  Sun

In [11]:
# 5. 조건식(필터링) 활용 (월급이 400 이상인 행의 '이름', '월급' 선택)
cond_loc = df.loc[df['tip'] >= 3, ['tip', 'total_bill', 'size']]
print(cond_loc)

      tip  total_bill  size
2    3.50       21.01     3
3    3.31       23.68     2
4    3.61       24.59     4
5    4.71       25.29     4
7    3.12       26.88     4
..    ...         ...   ...
232  3.39       11.61     2
234  3.00       15.53     2
238  4.67       35.83     3
239  5.92       29.03     3
243  3.00       18.78     2

[121 rows x 3 columns]

In [12]:
df['tip']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [13]:
first_row = df.iloc[0]
print(first_row)

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [14]:
res1 = df[df['total_bill'] > 30.0]
print(res1)

     total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
56        38.01   3.00    Male    Yes   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
112       38.07   4.00    Male     No   Sun  Dinner     3
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
167       31.71   4.50    Male     No   Sun  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3
173       31.85   3.18    Male    Yes   Sun  Dinner     2
175       32.90   3.11    Male    Yes   Sun  Dinner     2
179       34.63   3.55    Male    Yes   Sun  Dinner     2
180       34.65   3.68    Male    Yes   Sun  Dinner     4
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
187       30.46   2.00    Male    Yes   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
207       38.73   3.00    Male    Yes   Sat  Dinner     4
210       30.06   2.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
219       30.14   3.09  Female    Yes   Sat  Dinner     4
237       32.83   1.17    Male    Yes   Sat  Dinner     2
238       35.83   4.67  Female     No   Sat  Dinner     3

In [15]:
res2 = df[df['day'] == 'Sun']
print(res2)

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 7 columns]

In [16]:
print(res1[['total_bill', 'day']])

     total_bill   day
11        35.26   Sun
23        39.42   Sat
39        31.27   Sat
44        30.40   Sun
47        32.40   Sun
52        34.81   Sun
56        38.01   Sat
59        48.27   Sat
83        32.68  Thur
85        34.83  Thur
95        40.17   Fri
102       44.30   Sat
112       38.07   Sun
141       34.30  Thur
142       41.19  Thur
156       48.17   Sun
167       31.71   Sun
170       50.81   Sat
173       31.85   Sun
175       32.90   Sun
179       34.63   Sun
180       34.65   Sun
182       45.35   Sun
184       40.55   Sun
187       30.46   Sun
197       43.11  Thur
207       38.73   Sat
210       30.06   Sat
212       48.33   Sat
219       30.14   Sat
237       32.83   Sat
238       35.83   Sat

In [22]:
df[~((df['total_bill'] >= 30.0) & (df['day'] == 'Sun'))]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[230 rows x 7 columns]

In [24]:
target_days = ['Sun', 'Sat']
res_isin = df[df['day'].isin(target_days)]
print(res_isin)

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

In [25]:
 df['day']

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: str

In [26]:
df['day'].unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [ ]:
# tip이 2.0 이상 3.0 이하인 데이터 검색
# df[(df['tip'] >= 2.0) & (df['tip'] <= 3.0)] 와 동일
#inclusive: Literal['both', 'neither', 'left', 'right'] = "both”
res_between = df[df['tip'].between(2.0, 3.0)]

print(res_between[['tip', 'total_bill', 'day']].head())

     tip  total_bill  day
6   2.00        8.77  Sun
13  3.00       18.43  Sun
21  2.75       20.29  Sat
22  2.23       15.77  Sat
25  2.34       17.81  Sat

In [29]:
df.query('total_bill > 30.0 and day == "Sun"')

     total_bill   tip     sex smoker  day    time  size
11        35.26  5.00  Female     No  Sun  Dinner     4
44        30.40  5.60    Male     No  Sun  Dinner     4
47        32.40  6.00    Male     No  Sun  Dinner     4
52        34.81  5.20  Female     No  Sun  Dinner     4
112       38.07  4.00    Male     No  Sun  Dinner     3
156       48.17  5.00    Male     No  Sun  Dinner     6
167       31.71  4.50    Male     No  Sun  Dinner     4
173       31.85  3.18    Male    Yes  Sun  Dinner     2
175       32.90  3.11    Male    Yes  Sun  Dinner     2
179       34.63  3.55    Male    Yes  Sun  Dinner     2
180       34.65  3.68    Male    Yes  Sun  Dinner     4
182       45.35  3.50    Male    Yes  Sun  Dinner     3
184       40.55  3.00    Male    Yes  Sun  Dinner     2
187       30.46  2.00    Male    Yes  Sun  Dinner     5

In [30]:
df.sort_values(by="total_bill")

     total_bill    tip     sex smoker   day    time  size
67         3.07   1.00  Female    Yes   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
172        7.25   5.15    Male    Yes   Sun  Dinner     2
149        7.51   2.00    Male     No  Thur   Lunch     2
..          ...    ...     ...    ...   ...     ...   ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3
156       48.17   5.00    Male     No   Sun  Dinner     6
59        48.27   6.73    Male     No   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3

[244 rows x 7 columns]

In [31]:
df.sort_values(
    by="total_bill",
    ascending=False
)

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
156       48.17   5.00    Male     No   Sun  Dinner     6
182       45.35   3.50    Male    Yes   Sun  Dinner     3
..          ...    ...     ...    ...   ...     ...   ...
149        7.51   2.00    Male     No  Thur   Lunch     2
111        7.25   1.00  Female     No   Sat  Dinner     1
172        7.25   5.15    Male    Yes   Sun  Dinner     2
92         5.75   1.00  Female    Yes   Fri  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1

[244 rows x 7 columns]

In [32]:
df.sort_values(by="tip")

     total_bill    tip     sex smoker   day    time  size
92         5.75   1.00  Female    Yes   Fri  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
67         3.07   1.00  Female    Yes   Sat  Dinner     1
236       12.60   1.00    Male    Yes   Sat  Dinner     2
0         16.99   1.01  Female     No   Sun  Dinner     2
..          ...    ...     ...    ...   ...     ...   ...
141       34.30   6.70    Male     No  Thur   Lunch     6
59        48.27   6.73    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3

[244 rows x 7 columns]

In [33]:
df.sort_values(
    by="size",
    ascending=False
)

     total_bill   tip     sex smoker   day    time  size
156       48.17  5.00    Male     No   Sun  Dinner     6
141       34.30  6.70    Male     No  Thur   Lunch     6
143       27.05  5.00  Female     No  Thur   Lunch     6
125       29.80  4.20  Female     No  Thur   Lunch     6
187       30.46  2.00    Male    Yes   Sun  Dinner     5
..          ...   ...     ...    ...   ...     ...   ...
236       12.60  1.00    Male    Yes   Sat  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
82        10.07  1.83  Female     No  Thur   Lunch     1
67         3.07  1.00  Female    Yes   Sat  Dinner     1
222        8.58  1.92    Male    Yes   Fri   Lunch     1

[244 rows x 7 columns]

In [34]:
# 1. 인덱스를 섞어보기 (무작위 10개 추출)
sample = df.sample(10, random_state=42)
print(sample.head())

# 2. 인덱스 오름차순 정렬
print(sample.sort_index())

# 3. 인덱스 내림차순 정렬
print(sample.sort_index(
    ascending=False
))

# 4. 열(Column) 이름 정렬
# 열의 순서를 알파벳 순(sex, day, size, time, tip, total_bill 등)으로 정렬한다.
df.sort_index(axis=1)

     total_bill   tip     sex smoker   day    time  size
24        19.82  3.18    Male     No   Sat  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
153       24.55  2.00    Male     No   Sun  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
     total_bill   tip     sex smoker   day    time  size
6          8.77  2.00    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
24        19.82  3.18    Male     No   Sat  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
124       12.48  2.52  Female     No  Thur   Lunch     2
153       24.55  2.00    Male     No   Sun  Dinner     4
176       17.89  2.00    Male    Yes   Sun  Dinner     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
198       13.00  2.00  Female    Yes  Thur   Lunch     2
211       25.89  5.16    Male    Yes   Sat  Dinner     4
     total_bill   tip     sex smoker   day    time  size
211       25.89  5.16    Male    Yes   Sat  Dinner     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
176       17.89  2.00    Male    Yes   Sun  Dinner     2
153       24.55  2.00    Male     No   Sun  Dinner     4
124       12.48  2.52  Female     No  Thur   Lunch     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
24        19.82  3.18    Male     No   Sat  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2

      day     sex  size smoker    time   tip  total_bill
0     Sun  Female     2     No  Dinner  1.01       16.99
1     Sun    Male     3     No  Dinner  1.66       10.34
2     Sun    Male     3     No  Dinner  3.50       21.01
3     Sun    Male     2     No  Dinner  3.31       23.68
4     Sun  Female     4     No  Dinner  3.61       24.59
..    ...     ...   ...    ...     ...   ...         ...
239   Sat    Male     3     No  Dinner  5.92       29.03
240   Sat  Female     2    Yes  Dinner  2.00       27.18
241   Sat    Male     2    Yes  Dinner  2.00       22.67
242   Sat    Male     2     No  Dinner  1.75       17.82
243  Thur  Female     2     No  Dinner  3.00       18.78

[244 rows x 7 columns]